# Generated by Django 5.0.7 on 2024-07-19 00:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_customer_options_alter_customer_joined'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default=datetime.datetime(2024, 7, 19, 0, 40, 9, 369875, tzinfo=datetime.timezone.utc), max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='joined',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 19, 5, 39, 21, 728235)),
        ),
    ]
