# Generated by Django 5.0.7 on 2024-07-19 14:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_remove_user_phone_number_user_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='joined',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 19, 19, 39, 40, 349998)),
        ),
    ]
